# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: create-manifest
description: Create a Docker manifest for multi-architecture images.
inputs:
  components:
    description: "A list of components to create manifests for."
    required: true
  tag:
    description: "Tag to use for the manifest."
    required: false
    default: "latest"
  DOCKER_USERNAME:
    description: "Docker Hub username."
    required: true
  DOCKER_TOKEN:
    description: "Docker Hub token."
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
    - name: Docker login
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_TOKEN }}
    - name: Create manifest for ${{ inputs.component }}
      shell: bash
      run: |
        echo '${{ inputs.components }}' | yq -r '.[]' | while read -r component;
        do
          echo "Creating manifest for: $component"
          
          REPOSITORY=$(yq .$component.repository alliander_robotics/components.yml)
          
          docker buildx imagetools create -t \
          $REPOSITORY:${{ inputs.tag }} \
          $REPOSITORY:${{ inputs.tag }}-amd64 \
          $REPOSITORY:${{ inputs.tag }}-arm64
        done
