<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />

    <xacro:include filename="arm.xacro" />
    <xacro:include filename="arm_gazebo.xacro" />

   <!-- <xacro:include filename="camera.xacro" /> -->

   <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="arm_base_footprint" />
        <origin xyz="0 0 ${base_height + wheel_radius + 0.5*arm_base_height}" rpy="0 0 0"/>
    </joint>

</robot>