# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

axes:
  0:
    linear:
      profile: "A"
      direction: "y"
      flip: true
    angular:
      profile: "B"
      direction: "x"
  1:
    linear:
      profile: "A"
      direction: "x"
    angular:
      profile: "B"
      direction: "y"
  2:
    angular:
      direction: "z"
      flip: true
  3:
    linear:
      direction: "z"
      flip: true
  4: "switch_profile"

buttons:
  9: "open_gripper"
  10: "close_gripper"
