# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

################################ GENERAL CONFIG ################################

thread_priority: 40
publish_period: 0.001
max_expected_latency: 0.1
move_group_name: fr3_arm
active_subgroup: ""

############################# INCOMING COMMAND SETTINGS ########################
pose_command_in_topic: ~/pose_target_cmds
cartesian_command_in_topic: "~/delta_twist_cmds"
joint_command_in_topic: "~/delta_joint_cmds"
command_in_type: "unitless"
scale:
  linear: 0.4
  rotational: 0.8
  joint: 0.5
incoming_command_timeout: 0.1

################################ TWIST SETTINGS #################################

apply_twist_commands_about_ee_frame: true

############################ POSE TRACKING SETTINGS #############################

pose_tracking:
  linear_tolerance: 0.001
  angular_tolerance: 0.01

############################## OUTGOING COMMAND SETTINGS #######################

status_topic: "~/status"
command_out_topic: "/fr3_arm_controller/joint_trajectory"
command_out_type: "trajectory_msgs/JointTrajectory"
publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

############################## PLANNING SCENE MONITOR ##########################

monitored_planning_scene_topic: "/planning_scene"
joint_topic: "/joint_states"
check_octomap_collisions: false
is_primary_planning_scene_monitor: true

############################### SMOOTHING PLUGIN ###############################

use_smoothing: true
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

############################# COLLISION MONITOR ################################

check_collisions: true
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02
collision_check_rate: 10.0

############################# SINGULARITY CHECKING #############################

lower_singularity_threshold: 17.0
hard_stop_singularity_threshold: 30.0
leaving_singularity_threshold_multiplier: 2.0
singularity_step_scale: 0.01

############################### JOINT LIMITING #################################

halt_all_joints_in_joint_mode: true
halt_all_joints_in_cartesian_mode: true
joint_limit_margins: [0.1]
override_velocity_scaling_factor: 0.0
