# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff format
        entry: uv run ruff format
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: uv run ruff check
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: pydoclint
        name: pydoclint
        entry: bash -c "pydoclint *.py alliander_robotics --exclude=".venv/" -q"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check --error-on-warning
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: bash -c "uv run clang-format -i -Werror --dry-run $(find . -name *.cpp -o -name *.hpp -o -name *.c -o -name *.h | grep -v '.venv\|.nvim\|clangd')"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: bash -c "cppcheck --suppressions-list=.cppcheck-suppressions --enable=warning,performance,portability,style --error-exitcode=1 $(find . -name *.cpp | grep -v '.venv\|.nvim\|clangd')"
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: doxygen
        name: doxygen linting
        entry: ./doxygen-lint.sh
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: reuse
        name: reuse
        entry: uv run reuse lint
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: zizmor
        name: zizmor
        entry: uv run zizmor . --min-severity low --fix=all
        language: system
        pass_filenames: false
