# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

[tool.setuptools]
packages = ["alliander_robotics"]

[tool.setuptools.package-data]
alliander_robotics = ["**/*"]

[project]
name = "alliander_robotics"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "mashumaro>=3.17",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "termcolor>=3.3.0",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint]
select = ["I", "F", "E", "W", "B", "N", "A", "C4", "PL", "Q000", "SIM", "ANN", "ARG", "ERA", "D", "DOC"]
ignore = ["E501", "ANN204", "ANN401", "D100", "D104", "PLR0917", "PLR0914"]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
timeout = 60
timeout_func_only = true
timeout_method = "thread"
norecursedirs = ["install", "build", "log", ".venv", ".cache"]

# Settings of pydoclint, also in flake8 to use in vscode:
[tool.flake8]
style = "google"
skip-checking-short-docstrings = false
allow-init-docstring = true
check-style-mismatch = true
select = "DOC"

[tool.pydoclint]
style = "google"
skip-checking-short-docstrings = false
allow-init-docstring = true
check-style-mismatch = true
