#!/bin/bash

# SPDX-FileCopyrightText: Alliander N. V.
# 
# SPDX-License-Identifier: Apache-2.0

SCRIPT_DIR=$(
    cd "$(dirname "${BASH_SOURCE[0]}")" || exit
    pwd -P
)
SERVICE=rcdt_robotics

branch_name=$(git branch --show-current)
changed_files=($(git diff --name-only main))

image_tag="latest"
if [[ $branch_name != main ]] && [[ ${changed_files[@]} =~ dockerfiles/* || ${changed_files[@]} =~ .github/workflows/* ]]; then
    image_tag="${branch_name/\//-}-latest"
else
    docker pull ${image/rcdt_/rcdt\/}:$image_tag
fi

mkdir -p ~/.vscode-server
mkdir -p $SCRIPT_DIR/.config
touch $SCRIPT_DIR/.personal.bashrc

echo Running $SERVICE:$image_tag ...
IMAGE_TAG=$image_tag docker compose -f $SCRIPT_DIR/.devcontainer/docker-compose.yml run --rm rcdt_robotics
