#!/bin/bash

# SPDX-FileCopyrightText: Alliander N. V.
# 
# SPDX-License-Identifier: Apache-2.0

SCRIPT_DIR=$(
    cd "$(dirname "${BASH_SOURCE[0]}")" || exit
    pwd -P
)

branch_name=$(git branch --show-current)
if [[ $branch_name == main ]]; then
    image_tag="latest"
else
    image_tag="${branch_name/\//-}-latest"
fi

export IMAGE_TAG=$image_tag

mkdir -p ~/.vscode-server
mkdir -p $SCRIPT_DIR/.config
touch $SCRIPT_DIR/.personal.bashrc

echo Running $selected_image:$IMAGE_TAG ...
docker compose -f $SCRIPT_DIR/.devcontainer/docker-compose.yml run --rm rcdt_robotics
if [ $? -ne 0 ]; then
    export IMAGE_TAG="latest"
    echo Error finding image. Running $selected_image:$IMAGE_TAG instead ...
    docker compose -f $SCRIPT_DIR/.devcontainer/docker-compose.yml run --rm rcdt_robotics

fi