sonar.projectKey=alliander-opensource_alliander-robotics
sonar.organization=alliander-opensource

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/test/**,**/tests/**

sonar.exclusions=**/.venv/**,**/build/**,**/install/**,**/log/**,**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=
sonar.cpd.exclusions=
