# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0
services:
  alliander_ouster:
    image: allianderrobotics/ouster
    container_name: alliander_ouster
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    tty: true
    env_file:
      - .env
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev:/dev"
    command: ["/bin/bash", "-c", "ros2 launch alliander_ouster ouster.launch.py"]
