# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

# Based on: https://docs.nav2.org/configuration/packages/configuring-rotation-shim-controller.html

FollowPath:
  plugin: "nav2_rotation_shim_controller::RotationShimController"
  primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
  angular_dist_threshold: 0.785
  forward_sampling_distance: 0.5
  angular_disengage_threshold: 0.3925
  rotate_to_heading_angular_vel: 1.8
  max_angular_accel: 3.2
  simulate_ahead_time: 1.0
  rotate_to_goal_heading: false
