# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

# Based on: https://docs.nav2.org/configuration/packages/configuring-controller-server.html

controller_server:
  ros__parameters:
    enable_stamped_cmd_vel: true
    PathHandler:
      prune_distance: 5.5  # at least as large as furthest distance of interest by critic

