# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

## Based on https://docs.nav2.org/tutorials/docs/using_collision_monitor.html

collision_monitor:
  ros__parameters:
    base_frame_id: "panther/base_footprint"
    odom_frame_id: "panther/odom"
    cmd_vel_in_topic: "panther/cmd_vel_raw"
    cmd_vel_out_topic: "panther/cmd_vel"
    enable_stamped_cmd_vel: True
    transform_tolerance: 0.5
    polygons: ["PolygonSlow", "VelocityPolygonStop"]

    PolygonSlow:
      type: "polygon"
      points: "[[-1.5, 0.9], [1.5, 0.9], [1.5, -0.9], [-1.5, -0.9]]"
      action_type: "slowdown"
      min_points: 4
      slowdown_ratio: 0.7
      visualize: True
      polygon_pub_topic: "polygon_slower"
      enabled: True

    VelocityPolygonStop:
      type: "velocity_polygon"
      action_type: "stop"
      min_points: 6
      visualize: True
      enabled: True
      polygon_pub_topic: "velocity_polygon_stop"
      velocity_polygons: ["rotation", "translation_forward", "translation_backward", "stopped"]
      holonomic: false

      rotation:
        points: "[[0.65, 0.65], [0.65, -0.65], [-0.65, -0.65], [-0.65, 0.65]]"
        linear_min: 0.0
        linear_max: 0.05
        theta_min: -1.0
        theta_max: 1.0

      translation_forward:
        points: "[[0.90, 0.65], [0.90, -0.65], [-0.50, -0.65], [-0.50, 0.65]]"
        linear_min: 0.0
        linear_max: 1.0
        theta_min: -1.0
        theta_max: 1.0

      translation_backward:
        points: "[[0.50, 0.65], [0.50, -0.65], [-0.90, -0.65], [-0.90, 0.65]]"
        linear_min: -1.0
        linear_max: 0.0
        theta_min: -1.0
        theta_max: 1.0

      stopped:
        points: "[[0.60, 0.60], [0.60, -0.60], [-0.60, -0.60], [-0.60, 0.60]]"
        linear_min: -1.0
        linear_max: 1.0
        theta_min: -1.0
        theta_max: 1.0

    observation_sources: ["scan"]
    scan:
      source_timeout: 0.2
      type: "scan"
      topic: "/velodyne/scan"
      enabled: True