# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

# Based on: https://docs.nav2.org/configuration/packages/configuring-bt-navigator.html

controller_server:
  ros__parameters:
    enable_stamped_cmd_vel: true
