# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

vision_msgs/Point2D[] contour_2d
sensor_msgs/Image depth_image
sensor_msgs/CameraInfo camera_info
---
geometry_msgs/PointStamped[] contour_3d
bool success