# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "panther/base_link"
    odom_frame_id: "panther/odom"
    cmd_vel_in_topic: "panther/cmd_vel_raw"
    cmd_vel_out_topic: "panther/cmd_vel"
    transform_tolerance: 0.5
    source_timeout: 5.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop" and "slowdown" action types,
    # and robot footprint for "approach" action type.
    # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
    # or "circle" type with static footprint set by radius. "footprint_topic" parameter
    # to be ignored in circular case.
    polygons: ["PolygonSlower", "PolygonSlow"]
    PolygonSlower:
      type: "polygon"
      points: [
        -0.7,  0.55, 
         0.7,  0.55, 
         0.7, -0.55, 
        -0.7, -0.55
        ]
      action_type: "slowdown"
      max_points: 10
      slowdown_ratio: 0.1
      visualize: True
      polygon_pub_topic: "polygon_slower"
      enabled: True
    PolygonSlow:
      type: "polygon"
      points: [
        -1.2,  0.75, 
         1.2,  0.75,
         1.2, -0.75, 
        -1.2, -0.75
        ]
      action_type: "slowdown"
      max_points: 10
      slowdown_ratio: 0.3
      visualize: True
      polygon_pub_topic: "polygon_slow"
      enabled: True
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 2.0
      simulation_time_step: 0.1
      max_points: 5
      visualize: False
      enabled: True
    observation_sources: ["pointcloud"]
    scan:
      type: "scan"
      topic: "panther/velodyne/scan"
      enabled: True
    pointcloud:
      type: "pointcloud"
      topic: "panther/velodyne/scan/points"
      min_height: 0.1
      max_height: 1.0
      enabled: True