# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

frame: map
loops: 10
waypoints:
  # Example Inside IPKW path
  - [3.5, 3.5, 0.0]
  - [3.5, -3.5, 270]
  - [-3.5, -3.5, 180.0]
  - [-3.5, 3.5, 90]

    # Example outside IPKW path
  # - [11.0, 1.0, 0.0]
  # - [11.0, -4.0, 270]
  # - [5.0, -4.0, 180.0]
  # - [5.0, 1.0, 90]