# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

frame: map
loops: 10
waypoints:
  - [3.3, 3.3, 0.0]
  - [3.3, -3.3, 270]
  - [-3.3, -3.3, 180.0]
  - [-3.3, 3.3, 90]
