<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>

<!--
SPDX-FileCopyrightText: Alliander N. V.

SPDX-License-Identifier: Apache-2.0
-->

<package format="3">
  <name>alliander_tests</name>
  <version>0.1.0</version>
  <description>Contains the dependencies to run linting and pytest.</description>
  <maintainer email="robots@alliander.com">Alliander Robotics</maintainer>
  <license>Apache 2.0</license>

  <exec_depend>doxygen</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>nav2_simple_commander</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>

</package>