flowchart LR 
    subgraph C++
        subgraph MoveitManager
            subgraph GraspingManager
                create_point_cloud
                collision_filtering
                subgraph GraspModelWrapper
                    generate_grasps
                end
            end
        end
    end

    subgraph Python
        subgraph GraspGen
            GraspGenSampler.run_inference
        end
    end

    generate_grasps <--> GraspGenSampler.run_inference

    style C++ fill: #659AD2
    style Python fill: #FFD43B