# SPDX-FileCopyrightText: Alliander N. V.

# SPDX-License-Identifier: Apache-2.0

image: ipkw.pgm
mode: trinary
resolution: 0.05
origin: [-32.7, -25.1, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25