# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

sensor_msgs/Image mask
sensor_msgs/Image depth_image
sensor_msgs/CameraInfo camera_info
---
vision_msgs/Point2D[] contour
vision_msgs/Point2D[] box_contour
vision_msgs/Point2D centroid
float32 avg_hue
bool success
