# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0
services:
  alliander_openvla:
    image: allianderrobotics/openvla
    container_name: alliander_openvla
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    tty: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev:/dev"
      - "./models:/models"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    env_file:
      - .env
    command: ["/bin/bash", "-c", "ros2 launch alliander_openvla openvla.launch.py"]
