# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-workspace:
    runs-on: ubuntu-latest
    container: 
      image: rcdt/robotics
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: colcon build
        shell: bash -ieo pipefail {0} 
        run: |
            cd ros2_ws
            colcon build