# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: deploy-pr

on:
  pull_request:
    branches: [main]
    paths:
      - dockerfiles/**

jobs:
  docker:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set MODIFIED_BRANCH_NAME
        run: echo "MODIFIED_BRANCH_NAME=${GITHUB_HEAD_REF/\//-}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./dockerfiles
          file: ./dockerfiles/rcdt_robotics.Dockerfile
          tags: |
            rcdt/robotics:${{ env.MODIFIED_BRANCH_NAME }}-${{ github.sha }}
            rcdt/robotics:${{ env.MODIFIED_BRANCH_NAME }}-latest
