# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: deploy-pr

on:
  pull_request:
    branches: [main]
    # paths:
    #   - dockerfiles/**

jobs:
  docker:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./dockerfile/franka.Dockerfile
          tags: |
            rcdt/robotics:${{ GITHUB_HEAD_REF }}-latest
            rcdt/robotics:${{ GITHUB_HEAD_REF }}-$GITHUB_SHA
