# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: deploy-docker-image

on:
  workflow_call:
    inputs:
      container-image:
        type: string
        required: true

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: ./.github/actions/clear-disk-space
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./dockerfiles
          file: ./dockerfiles/rcdt_robotics.Dockerfile
          tags: ${{ inputs.container-image}}
          cache-from: type=registry,ref=rcdt/robotics:build-cache
          cache-to: type=registry,ref=rcdt/robotics:build-cache,mode=max
