# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: deploy-main

on:
  push:
    branches: [main]
    paths:
      - dockerfiles/**
      - .github/workflows/deploy-main.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Clear as much disk space as possible
        shell: bash
        run: |
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift
          df -h /
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set MODIFIED_BRANCH_NAME
        run: echo "MODIFIED_BRANCH_NAME=${GITHUB_HEAD_REF/\//-}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./dockerfiles
          file: ./dockerfiles/franka.Dockerfile
          tags: |
            rcdt/robotics:main-${{ github.sha }}
            rcdt/robotics:latest
          cache-from: type=registry,ref=rcdt/robotics:build-cache
          cache-to: type=registry,ref=rcdt/robotics:build-cache,mode=max
