# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: docker-and-workspace

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  define-variables:
    runs-on: ubuntu-latest
    outputs:
      running-local: ${{ steps.define-variables.outputs.running-local }}
      current-branch: ${{ steps.define-variables.outputs.current-branch }}
      image-tag: ${{ steps.define-variables.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: is-local
        if: ${{ env.ACT }}
        run: | 
          echo "Workflow is running locally using Nektos Act."
      - name: is-github
        if: ${{ !env.ACT }}
        run: | 
          echo "Workflow is running on Github."
      # - id: define-variables
      #   run: |
      #       echo "${env.ACT}"
          # running_local=$env.ACT
          # echo "running-local=${running-local}"

          # if [ ${running-local} ]; then
          #   current-branch=$(git branch --show-current)
          # else
          #   current-branch=${GITHUB_HEAD_REF/\//-}
          # fi
          # echo "current-branch=${current-branch}" >> "$GITHUB_OUTPUT"

          # image-tag=$(. ./get_image_tag)
          # echo "image-tag=${image-tag}" >> "$GITHUB_OUTPUT"
  # docker:
  #   needs: get-image-tag
  #   if: ${{ (needs.get-image-tag.outputs.image-tag != 'latest') || (github.event_name == 'push') }}
  #   uses: ./.github/workflows/reusable-docker.yml
  #   with:
  #     container-image: rcdt/robotics:${{ needs.get-image-tag.outputs.image-tag }}
  #   secrets: inherit
  # workspace:
  #   needs: [get-image-tag, docker]
  #   if: always()
  #   uses: ./.github/workflows/reusable-workspace.yml
  #   with:
  #     container-image: rcdt/robotics:${{ needs.get-image-tag.outputs.image-tag }}
