# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: docker-and-workspace

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  get-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.get-image-tag.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - id: get-image-tag
        name: define-docker-image-tag
        run: |
          git branch
          current_branch=${GITHUB_HEAD_REF/\//-}
          image_tag=$(. ./get_image_tag ${current_branch})
          echo "value=${image_tag}"
          echo "value=${image_tag}" >> "$GITHUB_OUTPUT"
  docker:
    needs: get-image-tag
    if: ${{ (needs.get-image-tag.outputs.image-tag != 'latest') || (github.event_name == 'push') }}
    uses: ./.github/workflows/reusable-docker.yml
    with:
      container-image: rcdt/robotics:${{ needs.get-image-tag.outputs.image-tag }}
    secrets: inherit
  workspace:
    needs: [get-image-tag, docker]
    if: always()
    uses: ./.github/workflows/reusable-workspace.yml
    with:
      container-image: rcdt/robotics:${{ needs.get-image-tag.outputs.image-tag }}
