name: documentation

# on:
#   push:
#     branches: [main]
#     paths:
#       - docs/**

on: [push]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
