# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: "documentation"

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/documentation.yml

jobs:
  # Based on: https://www.sphinx-doc.org/en/master/tutorial/deploying.html#
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: pip install sphinxcontrib-video
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs/build/html/
  # Based on: https://github.com/marketplace/actions/deploy-github-pages-site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
