# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: main

permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  push:
    branches: [main]

jobs:
  select-components:
    runs-on:
      group: managed
    outputs:
      UBUNTU_COMPONENTS: ${{ steps.variables.outputs.UBUNTU_COMPONENTS }}
      CUDA_COMPONENTS: ${{ steps.variables.outputs.CUDA_COMPONENTS }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - id: variables
        run: uv run github.py --select-components all

  build-ubuntu:
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner == 'ubuntu-24.04-arm' && 'mgd-ubuntu24-arm64-4c16g' || 'mgd-ubuntu24-x64-4c16g' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check architecture
        uses: ./.github/actions/check-architecture
        with:
          expected: ${{ matrix.runner }}
      - name: Deploy image
        uses: ./.github/actions/deploy-image
        with:
          component: base
          runner: ${{ matrix.runner }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-ubuntu-manifest:
    needs: build-ubuntu
    runs-on:
      group: managed
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Create manifest
        uses: ./.github/actions/create-manifest
        with:
          components: '["base"]'
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-ubuntu-images:
    needs: [select-components, build-ubuntu-manifest]
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
        component: ${{ fromJSON(needs.select-components.outputs.UBUNTU_COMPONENTS) }}
    runs-on: ${{ matrix.runner == 'ubuntu-24.04-arm' && 'mgd-ubuntu24-arm64-4c16g' || 'mgd-ubuntu24-x64-4c16g' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check architecture
        uses: ./.github/actions/check-architecture
        with:
          expected: ${{ matrix.runner }}
      - name: Deploy image
        uses: ./.github/actions/deploy-image
        with:
          component: ${{ matrix.component }}
          runner: ${{ matrix.runner }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-ubuntu-images-manifest:
    needs: [select-components, build-ubuntu-images]
    runs-on:
      group: managed
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Create manifest
        uses: ./.github/actions/create-manifest
        with:
          components: ${{ needs.select-components.outputs.UBUNTU_COMPONENTS}}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-cuda:
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner == 'ubuntu-24.04-arm' && 'mgd-ubuntu24-arm64-4c16g' || 'mgd-ubuntu24-x64-4c16g' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check architecture
        uses: ./.github/actions/check-architecture
        with:
          expected: ${{ matrix.runner }}
      - name: Deploy image
        uses: ./.github/actions/deploy-image
        with:
          component: cuda
          runner: ${{ matrix.runner }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-cuda-manifest:
    needs: build-cuda
    runs-on:
      group: managed
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Create manifest
        uses: ./.github/actions/create-manifest
        with:
          components: '["cuda"]'
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-cuda-images:
    needs: [select-components, build-cuda-manifest]
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
        component: ${{ fromJSON(needs.select-components.outputs.CUDA_COMPONENTS) }}
    runs-on: ${{ matrix.runner == 'ubuntu-24.04-arm' && 'mgd-ubuntu24-arm64-4c16g' || 'mgd-ubuntu24-x64-4c16g' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check architecture
        uses: ./.github/actions/check-architecture
        with:
          expected: ${{ matrix.runner }}
      - name: Deploy image
        uses: ./.github/actions/deploy-image
        with:
          component: ${{ matrix.component }}
          runner: ${{ matrix.runner }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-cuda-images-manifest:
    needs: [select-components, build-cuda-images]
    runs-on:
      group: managed
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Create manifest
        uses: ./.github/actions/create-manifest
        with:
          components: ${{ needs.select-components.outputs.CUDA_COMPONENTS }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  linting:
    runs-on:
      group: managed
    needs: [build-ubuntu-images, build-ubuntu-images-manifest, build-cuda-images, build-cuda-images-manifest]
    if: ${{ !failure() && !cancelled() }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Run linting in alliander_tests container
        run: uv run start.py --linting

  test:
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner == 'ubuntu-24.04-arm' && 'mgd-ubuntu24-arm64-4c16g' || 'mgd-ubuntu24-x64-4c16g' }}
    needs: [build-ubuntu-images, build-ubuntu-images-manifest, build-cuda-images, build-cuda-images-manifest]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check architecture
        uses: ./.github/actions/check-architecture
        with:
          expected: ${{ matrix.runner }}
      - name: Docker login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Run tests in alliander_tests container
        run: uv run start.py --pytest-no-nvidia --mode all
