# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: pr-closed

permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  remove-branch-images:
    runs-on:
      group: managed-linux
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Get token
        id: token
        run: |
          echo "TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKER_USERNAME }}\", \"password\": \"${{ secrets.DOCKER_TOKEN }}\"}" \
          https://hub.docker.com/v2/users/login/ \
          | jq -r .token)" >> $GITHUB_OUTPUT
      - name: Remove tags on Docker Hub
        run: uv run github.py --remove-tags-on-docker-hub ${{ steps.token.outputs.TOKEN }} --branch ${BRANCH_NAME}
