# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

franka:
  button: 0
  topic: "/franka/joy"
  moveit: true
panther:
  button: 1
  topic: "/panther/joy"
none:
  button: 2
