# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

franka:
  button: 0
  topic: "/franka/joy"
panther:
  button: 1
  topic: "/panther/joy"
none:
  button: 2
  topic: ""
panther_e_stop_reset:
  button: 11
  service: "/panther/hardware/e_stop_reset"
panther_e_stop_trigger:
  button: 12
  service: "/panther/hardware/e_stop_trigger"
