# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: deploy-image
description: Build and push a Docker image to Docker Hub.
inputs:
  component:
    description: "Component to deploy."
    required: true
  tag:
    description: "Tag to use for the image."
    required: false
    default: "latest"
  base_image_tag:
    description: "Tag to use for the base image."
    required: false
    default: "latest"
  runner:
    description: "Runner to use for deployment."
    required: true
  DOCKER_USERNAME:
    description: "Docker Hub username."
    required: true
  DOCKER_TOKEN:
    description: "Docker Hub token."
    required: true

runs:
  using: "composite"
  steps:
    - name: Set architecture
      shell: bash
      id: arch
      run: |
        if [[ "${RUNNER}" == *"-arm"* ]]; then
          echo "arch=arm64" >> $GITHUB_OUTPUT
        else
          echo "arch=amd64" >> $GITHUB_OUTPUT
        fi
      env:
        RUNNER: ${{ inputs.runner }}
    - name: Get variables for ${{ inputs.component }}
      shell: bash
      id: variables
      run: |
        echo "BASE_IMAGE=$(yq .${COMPONENT}.base_image alliander_robotics/components.yml)" >> $GITHUB_OUTPUT
        echo "REPOSITORY=$(yq .${COMPONENT}.repository alliander_robotics/components.yml)" >> $GITHUB_OUTPUT
        echo "DOCKERFILE=alliander_robotics/$(yq .${COMPONENT}.dockerfile alliander_robotics/components.yml)" >> $GITHUB_OUTPUT
      env:
        COMPONENT: ${{ inputs.component }}
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
    - name: Docker login
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_TOKEN }}
    - name: Build and push ${{ inputs.component }}-${{ steps.arch.outputs.arch }}
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        push: true
        context: .
        file: ${{ steps.variables.outputs.DOCKERFILE }}
        tags: ${{ steps.variables.outputs.REPOSITORY }}:${{ inputs.tag }}-${{ steps.arch.outputs.arch }}
        build-args: |
          BASE_IMAGE=${{ steps.variables.outputs.BASE_IMAGE }}:${{ inputs.base_image_tag }}
          SRC_DIRECTORY=alliander_robotics
        cache-from: |
          type=registry,ref=${{ steps.variables.outputs.REPOSITORY }}:${{ inputs.tag }}-${{ steps.arch.outputs.arch }}-cache
          type=registry,ref=${{ steps.variables.outputs.BASE_IMAGE}}:${{ inputs.tag }}-${{ steps.arch.outputs.arch }}-cache
          type=registry,ref=${{ steps.variables.outputs.REPOSITORY }}:latest-${{ steps.arch.outputs.arch }}-cache
          type=registry,ref=${{ steps.variables.outputs.BASE_IMAGE}}:latest-${{ steps.arch.outputs.arch }}-cache
        cache-to: |
          type=registry,ref=${{ steps.variables.outputs.REPOSITORY }}:${{ inputs.tag }}-${{ steps.arch.outputs.arch }}-cache,mode=max
